name: sahimed_commander
description: Internal deployment and automation tools for Sahimed.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  googleapis: ^13.0.0
  googleapis_auth: ^1.4.0
  path: ^1.8.3
